accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

covids/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('speech/', include('speech.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', RedirectView.as_view(url='speech/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

speech/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('speeches/', views.SpeechesListView.as_view(), name='speeches'),
    path('speeches/<int:pk>', views.SpeechesDetailView.as_view(), name='speech-detail'),

    path('speakers/', views.SpeakerListView.as_view(), name='speakers'),
    path('speaker/<int:pk>', views.SpeakerDetailView.as_view(), name='speaker-detail'),




]

accounts/models.py
from django.db import models

# Create your models here.

speech/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.utils import timezone

class Speeches(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    Speaker = models.ForeignKey('Speaker', on_delete=models.SET_NULL, null=True)
    Post_Summary = models.TextField(max_length=50000, help_text='Enter a brief description of the speech')
    date_of_post = models.DateField(null=True, blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('speech-detail', args=[str(self.id)])

class Speaker(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100, null=True, blank=True,)
    Bio = models.TextField(max_length=5000, null=True, blank=True, help_text='Enter a brief description of the speaker')


    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('speaker-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'


class Comment(models.Model):
    post = models.ForeignKey('Speeches', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

speech/views.py
from django.shortcuts import render,redirect, get_object_or_404
from speech.models import Speeches, Speaker
from django.views import generic



class SpeechesDetailView(generic.DetailView):
    model = Speeches


def index(request):

    return render(request, 'index.html')


class SpeechesListView(generic.ListView):
    model = Speeches
    paginate_by = 5

class SpeechesDetailView(generic.DetailView):
    model = Speeches
    

class SpeakerListView(generic.ListView):
    model = Speaker
    

class SpeakerDetailView(generic.DetailView):
    model = Speaker

accounts/templates/base.html
<!-- <!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html> -->

accounts/templates/home.html
<!-- {% extends 'base_generic.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %} -->

speech/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Covid Speeches</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <link rel="stylesheet" href="styles.css">
  <link rel="stylesheet" href="bootstrap.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% load static %}
  <link rel="stylesheet" href="{% static 'speech/styles.css' %}">

</head>
<body>
  
  <nav class=" navbar navbar-dark  fixed-top">

            <!-- Brand logo -->

            <div>
              <a href="{% url 'index' %}"><i class="fa fa-heartbeat" style="font-size:60px;color:red">
                <div class="w3-tag w3-xxxlarge w3-text-red">C</div><div class="w3-tag w3-xxxlarge w3-text-red">P</div><div class="w3-tag w3-xxxlarge w3-red w3-text-black
                ">U</div>
                
              </i></a>

            </div>

    <h1>Covid-19 Pandemic Update </h1>
    <div>
    <button class="navbar-toggler btn-outline-dark" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="collapsibleNavbar">

    <!-- links -->
    
    <ul class="navbar-nav">        
        <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'speeches' %}">Speeches</a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link" href="{% url 'speakers' %}">Speakers</a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link" href="https://www.worldometers.info/coronavirus/">
              <i class="material-icons" style="font-size:20px">public</i>WORLDOMETER</a>
        </li>
    </ul>

    </div>
</div>
</nav>


  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <nav class="w3-sidenav " >
        
          <a class="w3-border-bottom" href="{% url 'index' %}"><i class="fa fa-home w3-xxlarge"></i></a>
          <a class="w3-border-bottom" href="{% url 'speeches' %}">All Speeches</a>
          <a class="w3-border-bottom" href="{% url 'speakers' %}">All Speakers</a>
        
          <br><br>

        {% if user.is_authenticated %}
        <p3>Hi {{ user.username }}!</p3> <br><br>
        <p><a href="{% url 'logout' %}">Log Out</a></p> <br><br>
        
      {% else %}
        <p6>You are not logged in</p6> <br><br>
        <a class="w3-border-bottom" href="{% url 'login' %}">Log In <i class="fa fa-sign-in"></i> </a> 
        <a class="w3-border-bottom" href="{% url 'signup' %}" >Sign Up</a> <br>
        <a href="{% url 'password_reset' %}">Reset Password</a>
      {% endif %}
    
    </nav>
  </div>


     {% endblock %}
      
      <div class="col-sm-10 ">{% block content %}{% endblock %}{% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
      {% endblock %}</div>
    </div>
  </div>















         <!-- JS, Popper.js, and jQuery -->
         <script src="bootstrap.js"></script>
         <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
         <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
         <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
         
</body>
</html>

speech/templates/index.html
<!-- fixed bg -->
<div class="fixed-bg"></div>


{% extends "base_generic.html" %}

{% block content %}

<body>


<div>


  <div class="cards container">
    
    <div class="row">   

<!-- 1st card -->
        <div class="col-md-4 ">
         <div class="card">
          <div class="card-header" style="background-color: rgb(244, 250, 246);">
            <u> <h4 class="aside text-dark text-center"> About </h4> </u>
         </div>
          <div class="card-body text-center font-italic text-light" style="background-color:rgba(9, 133, 150, 0.822);">
            <ul class="list-group1">
              <p1>The CPU is your place for all updates on speeches accross the country
                on the covid-19 Pandemic. Get all your latest and old information on the 
                Presidents series of addressess to the nation concerning the Pandemic, as 
                well as press releases from the Ministry of Health and other speeches from 
                our honorable Ministers.
                Stay Safe. Wear a mask.
            </p1>            
          </ul>
      </div>
        <div class="card-footer text-danger text-center">
          <p> Always Remember to Wear A Mask</p>        
        </div>
         </div>
    </div>

<!-- 2nd card -->

        <div class="col-md-4">
        <div class="card">

          <div class="card-body text-center  font-italic text-light" style="background-color:rgba(105, 44, 42, 0.959);">
            <ul class="clicks">
              <p1>
                <br><br><br>
                <a href="{% url 'speakers' %}"><i class="fa fa-users" style="font-size:75px;"></i></a> <br>
                <p4>Click to view all speakers</p4>
                <br><br><br><br>

                <a href="{% url 'speeches' %}"><i class="fa fa-file-text" style="font-size:75px;"></i></a> <br>
                <p4>Click to view all speeches</p4>
                <br><br><br>


               
            </p1>            
          </ul>
      </div>

       <div class="card-footer text-danger text-center">
        <p> Always Remember to Wear A Mask</p>
    </div>
   </div>
 </div>


 <!-- 3rd card -->
        <div class="col-md-4 bg">
            <div class="card">
                <div class="card-header" style="background-color: rgb(244, 250, 246);">
                   <u> <h4 class="aside text-dark text-center"><i class="fa fa-newspaper-o" style="font-size:30px"></i> Latest News</h4> </u>
                </div>
                <div class="card-body text-center font-italic text-light" style="background-color:rgb(16, 39, 58);">


                        <div class="panel-body">

                    <ul class="list-group">
                    <li><a href="https://ghanahealthservice.org/covid19/">Update on the number of Covid-19 cases in 
                      Ghana</a></li><br>
                    
                    <li><a href="https://www.who.int/news/item/24-02-2021-covid-19-vaccine-doses-shipped-by-the-covax-facility-head-to-ghana-marking-beginning-of-global-rollout">
                      COVID-19 vaccine doses shipped by the COVAX Facility 
                      head to Ghana, marking beginning of global rollout</a></li><br>

                    <li><a href="https://citinewsroom.com/2021/02/manual-on-covid-19-vaccination-being-developed-for-public-sensitization-okoe-boye/">Manual on COVID-19 vaccination 
                      being developed for public sensitization – Okoe Boye</a></li><br>

                    <li><a href="https://www.aljazeera.com/news/2021/2/24/ghana-shuts-down-lgbt-office-rights-group">
                      Ghana security forces shut down LGBTQ office: Rights group</a></li><br>
                      
                    <li><a href="https://reliefweb.int/report/ghana/covid-19-patients-admission-receive-dignity-kits-who">
                      COVID-19 patients on admission receive Dignity Kits from WHO</a></li><br>

                    <li><a href="https://www.unicef.org/press-releases/ghana-becomes-recipient-historic-first-shipment-covax-vaccine">
                      Ghana becomes recipient of historic first shipment of COVAX vaccine</a></li><br>

                    <li><a href="https://reliefweb.int/report/world/latter-day-saint-charities-commits-us20-million-support-unicef-s-global-covid-19">
                      Latter-day Saint Charities Commits US$20 Million in Support of UNICEF’s Global COVID-19 Response</a></li><br>
                </ul>
                </div>
                    </div>
                 
           <div class="card-footer text-danger text-center" >
            <p>Click on the links above to read</p>
        </div>
       </div>
    </div>    
</div>
    
</div>





















<!-- <div class="container">
  <p>Welcome to this page, a website developed by <em>The Readers Club</em>!</p>

  <br/>
  <h2>About</h2>
  <p>The CPU is a your place for all updates on speeches accross the country
      on the covid-19 Pandemic. Get all your latest and old information on the 
      Presidents series of addressess to the nation concerning the Pandemic, as 
      well as press releases from the Ministry of Health and other speeches from 
      our honorable Ministers.
      Stay Safe. Wear a mask.
  </p>
  </div> -->

{% endblock %}

speech/templates/post_detail.html
{% extends 'base_generic.html' %} {% block content %}
{% load crispy_forms_tags %}



<div class="col-md-8 card mb-4  mt-3 ">
    <div class="card-body">
      <!-- comments -->
      {% with comments.count as total_comments %}
      <h2>{{ total_comments }} comments</h2>

      <p>
        {% endwith %} {% for comment in comments %}
      </p>

      <div class="comments" style="padding: 10px;">
        <p class="font-weight-bold">
          {{ comment.name }}
          <span class=" text-muted font-weight-normal">
            {{ comment.created_on }}
          </span>
        </p>
        {{ comment.body | linebreaks }}
      </div>

      {% endfor %}
    </div>
  </div>
  <div class="col-md-8 card mb-4  mt-3 ">
    <div class="card-body">
      {% if new_comment %}
      <div class="alert alert-success" role="alert">
        Your comment is awaiting moderation
      </div>
      {% else %}
      <h3>Leave a comment</h3>
      <form method="post" style="margin-top: 1.3em;">
        {{ comment_form | crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
      </form>
      {% endif %}
    </div>
  </div>
</div>
</div>
{% endblock content %}

speech/templates/speech/speaker_detail.html
<div class="whole text-center">

{% extends "base_generic.html" %}

{% block content %}
<div class="spc-list">

  <u><h2>Speaker: {{ speaker.first_name }} {{speaker.last_name}}</h2></u>
  <p><strong>Bio:</strong>  {{ speaker.Bio }}</p>


  <div style="margin-left:20px;margin-top:20px">
    
    
    <u><h3>Speaker's Speeches</h3></u>
    {% for speeches in speaker.speeches_set.all %}
    <hr>    
    <li>
        <a href="{{ speeches.get_absolute_url }}">{{speeches.title}}</a> {{speeches.date_of_post}}
    </li>
   

    {% endfor %}
  </div>
{% endblock %}
</div>
</div>

speech/templates/speech/speaker_list.html
<div class="try">
{% extends "base_generic.html" %}

{% block content %}

<div class="spc-list">
  <u><h2>Speaker List</h2></u>
  {% if speaker_list %}
  <strong><ul>
    {% for speaker in speaker_list %}
      <li>
        <a href="{{ speaker.get_absolute_url }}">{{ speaker }}</a>
      </li>
    {% endfor %}
  </ul></strong>
  {% else %}
    <p>There are no Speakers available.</p>
  {% endif %} 
{% endblock %}
</div>
</div>

speech/templates/speech/speeches_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="spc-list">
  <u><h2>Title: {{ speeches.title }}</h2></u>
  <p><strong>Date:</strong> {{ speeches.date_of_post }}</p>

  <p><strong>Speaker:</strong> <a href="{% url 'speaker-detail' speeches.Speaker.pk %}">{{ speeches.Speaker }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Speech:</strong> " {{ speeches.Post_Summary }} "</p>



  <hr>
  <u><h3>Comments</h3></u>
{% for comment in speeches.comments.all %}

    <div class="comment">
       
        <strong>{{ comment.author }}</strong>
        <p><strong>{{ comment.text }}</strong> <small>{{ comment.created_date|timesince }} ago</small></p>       
    </div>
{% empty %}
    <p>No comments here yet :(</p> 


{% endfor %}

{% endblock %}
</div>

speech/templates/speech/speeches_list.html
<div class="try">

{% extends "base_generic.html" %}
{% block content %}


<div class="spc-list">
  <u><h2>Speeches & Press Releases</h2></u>
  {% if speeches_list %}
  <strong><ul>
    {% for speeches in speeches_list %}
      <li>
        <a href="{{ speeches.get_absolute_url }}">{{ speeches.title }}</a> 
        <a href="{% url 'speaker-detail' speeches.Speaker.pk %}">||{{speeches.Speaker}}||</a>
        
        <p6>({{ speeches.date_of_post }})</p6>

      <!--   <p><a href="{{ speeches.get_absolute_url }}">Comments: {{ speeches.comments.count }}</a></p>
 -->

      </li>
    {% endfor %}
  </ul></strong>
  {% else %}
    <p>There are no speeches available.</p>
  {% endif %} 

{% endblock %}
</div>
</div>